import { pgTable, bigint, text, jsonb, numeric, timestamp, index, unique } from 'drizzle-orm/pg-core';
import { bytes } from './types.js';
import type { GuardAvailabilityManifest, GuardRevisionEvent, GuardStoredEvidence, GuardStoredCoverage, GuardStoredRole, GuardVerdictRevisionInput } from '@eko/shared';
// Guard §7.2: each table has one writer, declared in GUARD_STORAGE_WRITERS.
const position = (name: string) => numeric(name).array().notNull();
const common = () => ({
  id: text('id').primaryKey(), sourceKey: text('source_key').notNull().unique(), chainId: bigint('chain_id', { mode: 'number' }).notNull(), coin: text('coin').notNull(),
  manifestId: text('manifest_id').notNull().references(() => guardAvailability.id), sourceRevision: text('source_revision').notNull(),
  statePosition: position('state_position'), stateHash: text('state_hash').notNull(), knownPosition: position('known_position'), knownHash: text('known_hash').notNull(), acquisitionSequence: numeric('acquisition_sequence', { precision: 78, scale: 0 }).notNull(), dependencyIds: text('dependency_ids').array().notNull(),
  payloadHash: text('payload_hash').notNull(), objectRef: text('object_ref').notNull(), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull(),
});
export const guardAvailability = pgTable('guard_availability', { id: text('id').primaryKey(), chainId: bigint('chain_id', { mode: 'number' }).notNull(), sourceId: text('source_id').notNull(), sourceRevision: text('source_revision').notNull(), replayMode: text('replay_mode').notNull(), acquisitionSequence: numeric('acquisition_sequence', { precision: 78, scale: 0 }).notNull(), knownPosition: position('known_position'), watermarkPosition: position('watermark_position'), data: jsonb('data').$type<GuardAvailabilityManifest>().notNull(), acquiredAt: timestamp('acquired_at', { withTimezone: true }).notNull() }, t => [unique().on(t.chainId, t.sourceId, t.sourceRevision, t.replayMode, t.acquisitionSequence)]);
export const guardChainEvidence = pgTable('guard_chain_evidence', { ...common(), data: jsonb('data').$type<GuardStoredEvidence>().notNull(), content: bytes('content').notNull() }, t => [index('guard_chain_evidence_known').on(t.chainId, t.coin, t.knownPosition, t.acquisitionSequence), index('guard_chain_evidence_dependencies').using('gin', t.dependencyIds)]);
export const guardRoles = pgTable('guard_roles', { ...common(), data: jsonb('data').$type<GuardStoredRole>().notNull(), content: bytes('content').notNull() }, t => [index('guard_roles_known').on(t.chainId, t.coin, t.knownPosition, t.acquisitionSequence), index('guard_roles_dependencies').using('gin', t.dependencyIds)]);
export const guardSourceCoverage = pgTable('guard_source_coverage', { ...common(), data: jsonb('data').$type<GuardStoredCoverage>().notNull() }, t => [index('guard_source_coverage_known').on(t.chainId, t.coin, t.knownPosition, t.acquisitionSequence), index('guard_source_coverage_dependencies').using('gin', t.dependencyIds)]);
export const guardMeasurementEvidence = pgTable('guard_measurement_evidence', { ...common(), data: jsonb('data').$type<GuardStoredEvidence>().notNull(), content: bytes('content').notNull() }, t => [index('guard_measurement_evidence_known').on(t.chainId, t.coin, t.knownPosition, t.acquisitionSequence), index('guard_measurement_evidence_dependencies').using('gin', t.dependencyIds)]);
export const guardCheckCoverage = pgTable('guard_check_coverage', { ...common(), data: jsonb('data').$type<GuardStoredCoverage>().notNull() }, t => [index('guard_check_coverage_known').on(t.chainId, t.coin, t.knownPosition, t.acquisitionSequence), index('guard_check_coverage_dependencies').using('gin', t.dependencyIds)]);
export const guardVerdictRevisions = pgTable('guard_verdict_revisions', { ...common(), data: jsonb('data').$type<GuardVerdictRevisionInput>().notNull(), semanticHash: text('semantic_hash').notNull(), receiptId: text('receipt_id').notNull().unique(), supersedes: text('supersedes') }, t => [index('guard_verdict_revisions_known').on(t.chainId, t.coin, t.knownPosition, t.acquisitionSequence), index('guard_verdict_revisions_dependencies').using('gin', t.dependencyIds)]);
const events = () => ({ id: text('id').primaryKey(), targetId: text('target_id').notNull(), kind: text('kind').notNull(), replacementId: text('replacement_id'), causeId: text('cause_id').notNull(), knownPosition: position('known_position'), acquisitionSequence: numeric('acquisition_sequence', { precision: 78, scale: 0 }).notNull(), data: jsonb('data').$type<GuardRevisionEvent>().notNull(), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull() });
export const guardSourceEvents = pgTable('guard_source_events', events(), t => [unique().on(t.targetId, t.kind, t.causeId), index('guard_source_events_target').on(t.targetId, t.knownPosition, t.acquisitionSequence)]);
export const guardMeasurementEvents = pgTable('guard_measurement_events', events(), t => [unique().on(t.targetId, t.kind, t.causeId), index('guard_measurement_events_target').on(t.targetId, t.knownPosition, t.acquisitionSequence)]);
export const guardVerdictEvents = pgTable('guard_verdict_events', events(), t => [unique().on(t.targetId, t.kind, t.causeId), index('guard_verdict_events_target').on(t.targetId, t.knownPosition, t.acquisitionSequence)]);
export const guardVerdictRuns = pgTable('guard_verdict_runs', { runId: text('run_id').primaryKey(), revisionId: text('revision_id').notNull().references(() => guardVerdictRevisions.id), recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull() });

// Receipts-owned immutable public bytes and authenticated registry events (§7.3).
export const guardReceiptPayloads = pgTable('guard_receipt_payloads', { id:text('id').primaryKey(), revisionId:text('revision_id').notNull().unique().references(()=>guardVerdictRevisions.id), chainId:bigint('chain_id',{mode:'number'}).notNull(), payloadHash:text('payload_hash').notNull(), canonicalPayload:text('canonical_payload').notNull(), data:jsonb('data').$type<import('@eko/shared').GuardReceiptPayload>().notNull(), recordedAt:timestamp('recorded_at',{withTimezone:true}).notNull() });
export const guardReceiptAnchors = pgTable('guard_receipt_anchors', { id:text('id').primaryKey(), receiptId:text('receipt_id').notNull().references(()=>guardReceiptPayloads.id), chainId:bigint('chain_id',{mode:'number'}).notNull(), registryAddress:text('registry_address').notNull(), batchId:numeric('batch_id',{precision:20,scale:0}).notNull(), data:jsonb('data').notNull(), recordedAt:timestamp('recorded_at',{withTimezone:true}).notNull() });
export const guardReceiptAnchorEvents = pgTable('guard_receipt_anchor_events', { id:text('id').primaryKey(), anchorId:text('anchor_id').notNull().references(()=>guardReceiptAnchors.id), kind:text('kind').notNull(), data:jsonb('data').notNull(), recordedAt:timestamp('recorded_at',{withTimezone:true}).notNull() });
