import type { Page } from '@playwright/test';
import { createWalletClient, http, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { robinhood } from 'viem/chains';

/**
 * A test-only EIP-1193 wallet announced via EIP-6963. Keys are generated by the test at runtime;
 * signing happens in the Node test process (exposed functions). Nothing touches a real wallet.
 */
export async function installMockWallet(page: Page, opts: { key: Hex; chainId: number; rpcUrl?: string; rejectSend?: boolean }) {
  const account = privateKeyToAccount(opts.key);
  await page.exposeFunction('__mockSign', async (message: string) => account.signMessage({ message: message.startsWith('0x') ? { raw: message as Hex } : message }));
  await page.exposeFunction('__mockSend', async (tx: { to: Hex; data?: Hex; value?: Hex }) => {
    if (!opts.rpcUrl) throw new Error('no rpc');
    const wc = createWalletClient({ account, chain: { ...robinhood, rpcUrls: { default: { http: [opts.rpcUrl] } } }, transport: http(opts.rpcUrl) });
    return wc.sendTransaction({ to: tx.to, data: tx.data, value: tx.value ? BigInt(tx.value) : 0n });
  });
  await page.exposeFunction('__mockRpc', async (method: string, params: unknown[]) => {
    if (!opts.rpcUrl) throw new Error('no rpc');
    const r = await fetch(opts.rpcUrl, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) });
    const j = await r.json();
    if (j.error) throw new Error(j.error.message);
    return j.result;
  });
  await page.addInitScript(
    ({ address, chainId, rejectSend }) => {
      let chain = chainId;
      let connected = false;
      const listeners: Record<string, ((...a: unknown[]) => void)[]> = {};
      const emit = (e: string, ...a: unknown[]) => (listeners[e] ?? []).forEach((f) => f(...a));
      const w = window as unknown as Record<string, (...a: unknown[]) => Promise<unknown>>;
      const provider = {
        isMockWallet: true,
        on: (e: string, f: (...a: unknown[]) => void) => ((listeners[e] ??= []).push(f), provider),
        removeListener: (e: string, f: (...a: unknown[]) => void) => ((listeners[e] = (listeners[e] ?? []).filter((x) => x !== f)), provider),
        async request({ method, params }: { method: string; params?: unknown[] }) {
          switch (method) {
            case 'eth_requestAccounts':
              connected = true;
              emit('accountsChanged', [address]);
              return [address];
            case 'eth_accounts':
              // Like real wallets: no accounts are exposed until the user approves a connection.
              return connected ? [address] : [];
            case 'eth_chainId':
              return `0x${chain.toString(16)}`;
            case 'wallet_switchEthereumChain': {
              const id = parseInt((params?.[0] as { chainId: string }).chainId, 16);
              chain = id;
              emit('chainChanged', `0x${id.toString(16)}`);
              return null;
            }
            case 'wallet_addEthereumChain':
              return null;
            case 'personal_sign':
              return w.__mockSign!((params as string[])[0]);
            case 'eth_sendTransaction':
              if (rejectSend) throw Object.assign(new Error('User rejected the request.'), { code: 4001 });
              return w.__mockSend!((params as unknown[])[0]);
            case 'wallet_getPermissions':
            case 'wallet_requestPermissions':
              return [{ parentCapability: 'eth_accounts' }];
            default:
              return w.__mockRpc!(method, params ?? []);
          }
        },
      };
      const info = { uuid: 'b6c6c0f0-0000-4000-8000-000000000001', name: 'Test Wallet', icon: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"/>', rdns: 'test.eko.wallet' };
      const announce = () => window.dispatchEvent(new CustomEvent('eip6963:announceProvider', { detail: Object.freeze({ info, provider }) }));
      window.addEventListener('eip6963:requestProvider', announce);
      announce();
    },
    { address: account.address, chainId: opts.chainId, rejectSend: !!opts.rejectSend },
  );
  return account;
}
