// Builds the SignalOS marketing kit: PNG logos + app icons, social templates, stickers, tokens, zip.
// Run: pnpm brand:build   (uses the locally installed Google Chrome through Playwright)
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const brand = join(here, '..');
const repo = join(brand, '..');
const pub = join(repo, 'apps/web/public/brand');
const require = createRequire(join(repo, 'apps/web/package.json'));
const { chromium } = require('@playwright/test');

const T = {
  color: {
    sky: { value: '#4EB7FA', job: 'The header and brand surface' },
    blue: { value: '#2F95FF', job: 'Primary actions, selection, AI at work, paper mode' },
    navy: { value: '#05090D', job: 'Product background' },
    card: { value: '#0C1216', job: 'Cards and panels' },
    ink: { value: '#0A1624', job: 'Text and marks on sky' },
    mint: { value: '#19D99F', job: 'Buy and gains. Reserved.' },
    red: { value: '#F0445A', job: 'Sell and losses. Reserved.' },
    live: { value: '#FF4FA8', job: 'Real-money mode' },
    testnet: { value: '#A996FF', job: 'Testnet mode' },
    amber: { value: '#FFB547', job: 'Warnings and set-up prompts' },
  },
  product: {
    'bg-0': '#05090D', 'bg-1': '#080D12', 'bg-2': '#0C1216', 'bg-3': '#111920', 'bg-4': '#18222B', 'bg-5': '#213039', 'bg-select': '#0F294C',
    'text-1': '#F2F6FA', 'text-2': '#B4C0CC', 'text-3': '#7C8997', 'sky-hi': '#7CCBFD', 'blue-hi': '#5AABFF', 'blue-deep': '#1466D6', 'mint-deep': '#0EA877', 'red-deep': '#C42A41',
  },
  font: {
    display: { family: 'Anton', weight: 400, style: 'slanted 12°, uppercase', tracking: '0.005em', license: 'SIL OFL 1.1' },
    ui: { family: 'Geist', weight: '400–750', license: 'SIL OFL 1.1' },
    numbers: { family: 'Geist Mono', feature: 'tnum, zero', license: 'SIL OFL 1.1' },
  },
  radius: { xs: 4, sm: 7, md: 9, lg: 12, xl: 16, '2xl': 22 },
  gradient: { header: 'linear-gradient(90deg, #4BB1F8 0%, #4EB7FA 45%, #74C6FC 100%)', crew: 'linear-gradient(100deg, #2A8FF8 0%, #3AA3FD 55%, #52B2FF 100%)' },
};

const out = (...p) => {
  const f = join(brand, ...p);
  mkdirSync(dirname(f), { recursive: true });
  return f;
};

// 1) Tokens
writeFileSync(out('tokens/tokens.json'), JSON.stringify(T, null, 2) + '\n');
writeFileSync(
  out('tokens/tokens.css'),
  `/* SignalOS brand tokens (generated by brand/scripts/build-kit.mjs) */\n:root {\n${Object.entries(T.color)
    .map(([k, v]) => `  --sos-${k}: ${v.value}; /* ${v.job} */`)
    .join('\n')}\n${Object.entries(T.product)
    .map(([k, v]) => `  --sos-${k}: ${v};`)
    .join('\n')}\n  --sos-header-grad: ${T.gradient.header};\n  --sos-font-display: 'Anton', Impact, ui-sans-serif, sans-serif;\n  --sos-font-ui: 'Geist', ui-sans-serif, system-ui, sans-serif;\n  --sos-font-num: 'Geist Mono', ui-monospace, monospace;\n}\n`,
);

const browser = await chromium.launch({ channel: process.env.PW_CHANNEL ?? 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 2400, height: 2600 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();

// 2) Logo PNGs and app icons
async function svgToPng(file, dest, width, bg = 'transparent') {
  // Inline the SVG markup (outlined paths, no external refs) so no file:// access is needed.
  const svgText = readFileSync(join(brand, 'logo', file), 'utf8').replace(/<svg /, '<svg id="i" preserveAspectRatio="xMidYMid meet" ');
  await page.setContent(`<html><body style="margin:0;background:${bg}"><div style="width:${width}px">${svgText}</div><style>#i{display:block;width:${width}px;height:auto}</style></body></html>`);
  const box = await page.locator('#i').boundingBox();
  if (!box || box.width < 4 || box.height < 4) throw new Error(`empty render for ${file}`);
  await page.locator('#i').screenshot({ path: out(dest), omitBackground: bg === 'transparent' });
}
for (const f of readdirSync(join(brand, 'logo')).filter((f) => f.startsWith('lockup-') || f.startsWith('stacked-') || f.startsWith('symbol'))) {
  const w = f.startsWith('symbol') ? 512 : f.startsWith('stacked') ? 900 : 1400;
  await svgToPng(f, `png/${f.replace('.svg', '@2x.png')}`, w);
}
for (const s of [1024, 512, 192, 180, 64, 32]) await svgToPng('app-icon.svg', `png/app-icon-${s}.png`, s);
await svgToPng('app-icon-sky.svg', 'png/app-icon-sky-1024.png', 1024);

// 3) Templates (social + stickers): one artboard per <section class="ab" id="...">
async function renderTemplate(file, dir, { transparent = false } = {}) {
  await page.goto(pathToFileURL(join(brand, 'templates', file)).href);
  await page.evaluate(() => window.__kitReady);
  await page.waitForTimeout(300);
  const ids = await page.$$eval('section.ab', (els) => els.map((e) => e.id));
  for (const id of ids) {
    const box = await page.locator(`#${id}`).boundingBox();
    await page.setViewportSize({ width: Math.max(2400, Math.ceil(box.width + 120)), height: Math.max(2600, Math.ceil(box.y + box.height + 60)) });
    await page.locator(`#${id}`).screenshot({ path: out(`${dir}/${id}.png`), omitBackground: transparent });
    console.log(`  ${dir}/${id}.png  ${Math.round(box.width)}×${Math.round(box.height)}`);
  }
}
await renderTemplate('social.html', 'social');
await renderTemplate('stickers.html', 'stickers', { transparent: true });
await browser.close();

// 4) Publish to the web app and zip the kit
for (const d of ['logo', 'png', 'social', 'stickers', 'tokens', 'fonts', 'copy']) {
  if (existsSync(join(pub, d))) rmSync(join(pub, d), { recursive: true });
  cpSync(join(brand, d), join(pub, d), { recursive: true });
}
cpSync(join(brand, 'GUIDELINES.md'), join(pub, 'GUIDELINES.md'));
const zip = join(pub, 'signalos-brand-kit.zip');
rmSync(zip, { force: true });
execFileSync('zip', ['-rqX', zip, 'README.md', 'GUIDELINES.md', 'logo', 'png', 'social', 'stickers', 'tokens', 'fonts', 'copy', 'templates', '-x', '*.DS_Store'], { cwd: brand });
console.log('kit built → brand/ and apps/web/public/brand/ (+ signalos-brand-kit.zip)');
