import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const require = createRequire(import.meta.url);
mkdirSync('coverage', { recursive: true });
rmSync('coverage/core-summary.json', { force: true });
let failed = false;
try {
  const vitest = require('vitest/package.json').version;
  const provider = require('@vitest/coverage-v8/package.json').version;
  if (provider !== vitest) throw new Error(`Coverage provider ${provider} does not match Vitest ${vitest}`);
  // Instrumented suites are CPU-heavy; two workers keep hard-coded per-test limits reliable on loaded machines.
  const env = { ...process.env, VITEST_MAX_WORKERS: process.env.VITEST_MAX_WORKERS ?? '2' };
  const result = spawnSync('pnpm', ['exec', 'vitest', 'run', '--config', 'vitest.coverage.config.ts', '--coverage'], { stdio: 'inherit', env });
  failed = result.status !== 0 || !!result.error;
} catch (error) {
  console.error(error.code === 'MODULE_NOT_FOUND'
    ? 'TypeScript coverage unavailable: install @vitest/coverage-v8 at the exact installed Vitest version and update the lockfile. See docs/security/COVERAGE.md.'
    : error.message);
  failed = true;
}
// A missing TS provider must not hide the independently measurable Solidity result.
const contracts = spawnSync('pnpm', ['--filter', '@eko/contracts', 'coverage'], { encoding: 'utf8' });
const report = `${contracts.stdout ?? ''}${contracts.stderr ?? ''}`;
writeFileSync('coverage/contracts-summary.txt', report);
process.stdout.write(report);
if (contracts.error) console.error(contracts.error.message);
if (contracts.status !== 0 || contracts.error) failed = true;
// Publish counters only from the reports generated by this invocation. Failed runs
// may help diagnosis but cannot establish the aggregate target.
if (!failed) {
  try {
    const typescript = JSON.parse(readFileSync('coverage/typescript/coverage-summary.json', 'utf8')).total.lines;
    const total = report.split('\n').find(line => /^\s*\| Total\s*\|/.test(line));
    const lines = total?.match(/(\d+(?:\.\d+)?)% \((\d+)\/(\d+)\)/);
    if (!lines) throw new Error('Solidity executable line counters unavailable');
    const solidity = { covered: Number(lines[2]), total: Number(lines[3]) };
    if (!Number.isInteger(typescript.covered) || !Number.isInteger(typescript.total) || typescript.total <= 0 || solidity.total <= 0)
      throw new Error('Invalid executable line counters');
    const aggregate = { covered: typescript.covered + solidity.covered, total: typescript.total + solidity.total };
    aggregate.pct = 100 * aggregate.covered / aggregate.total;
    writeFileSync('coverage/core-summary.json', JSON.stringify({ typescript, solidity, aggregate }, null, 2) + '\n');
    console.log(`Aggregate core lines: ${aggregate.covered}/${aggregate.total} (${aggregate.pct.toFixed(4)}%)`);
    if (aggregate.covered * 100 < aggregate.total * 95) {
      console.error('Aggregate core line coverage is below 95%');
      failed = true;
    }
  } catch (error) { console.error(error.message); failed = true; }
}
process.exitCode = failed ? 1 : 0;
