import { APP_NAME } from './shell';
export const MISSION_COPY = {
  connectToCreate: 'Connect and verify your wallet to create the agent and its key. Every step is here to read first.',
  overviewIntro: 'Your trading agents ask EKO before every order. You set their limits and answer anything above them.',
  approvalsIntro: 'Orders your agents want to place above your limits. You decide here on the web; unanswered approvals expire and the agent is told no.',
  connectIntro: `Add ${APP_NAME} next to your agent’s Robinhood connection. It gets Senses, Guardrails and a Flight Recorder; you supervise it in Mission Control.`,
  credentials: `${APP_NAME} never receives your Robinhood credentials. Your agent keeps its own Robinhood connection.`,
  keyOnce: 'You won’t see this again. Store it in your agent’s config. Stored nowhere else in this browser.',
  connectorNote: `Works on every Claude plan; Free allows one custom connector. On Team and Enterprise, an owner adds ${APP_NAME} first in Organization settings → Connectors, then members connect.`,
  previewPreset: 'Preset preview. Editable fields and saving arrive at token launch.',
  journalNote: 'Older entries stay in the Flight Recorder, encrypted to you. Agent notes are shown as plain text and never read as instructions.',
  unchecked: 'Your agent placed this without checking. Re-send the harness instructions, or stop the agent.',
  performanceNote: 'Positions and fills are self-reported by the agent from its own venue connection. Past results don’t predict future ones. Not financial advice.',
  robinhoodConnection: `Your agent connects to Robinhood’s MCP on its own. ${APP_NAME} never receives your Robinhood credentials and can’t place, block or cancel orders there. Check that Robinhood’s own trade approvals are on.`,
  pendingVerify: 'Waiting for your agent’s first call…',
  connected: 'First journal event received',
};
export const PLATFORM_COPY = {
  claude_connector: ['Claude Desktop and claude.ai', 'Custom connector. You sign in with OAuth; there’s no key to copy.'],
  claude_code: ['Claude Code', 'One command in your terminal, with a harness API key.'],
  claude_desktop: ['Claude Desktop', 'One config entry and a local bridge (Node.js), with a harness API key.'],
  chatgpt: ['ChatGPT', 'Connector with OAuth sign-in, like the Claude app.'],
  openclaw: ['OpenClaw', `MCP config plus the ${APP_NAME} skill, with an API key.`],
  generic_mcp: ['Generic MCP', 'Any client that speaks MCP over Streamable HTTP.'],
  onchain: ['On-chain agent', 'Session-key limits enforced on-chain once reviewed.'],
} as const;
export const POLICY_FIELDS = [
  { key: 'maxPositionUsd', label: 'Max order size', hint: 'The largest single order preflight allows.', unit: '$', group: 'Size and loss' },
  { key: 'maxPositionPct', label: 'Max position share', hint: 'Maximum share of the portfolio in a position.', unit: '%', group: 'Size and loss' },
  { key: 'maxDailyLossUsd', label: 'Daily loss limit', hint: 'After this loss, every preflight returns deny until tomorrow.', unit: '$', group: 'Size and loss' },
  { key: 'approvalAboveUsd', label: 'Approval above', hint: 'Larger orders need your approval.', unit: '$', group: 'Size and loss' },
  { key: 'maxLeverage', label: 'Max leverage', hint: 'Orders above this leverage are denied.', unit: '×', group: 'Size and loss' },
  { key: 'maxRoundTripCostPct', label: 'Max exit cost', hint: 'Round-trip cost at the order size, from the buy-then-sell simulation.', unit: '%', group: 'Coin checks' },
  { key: 'minLiquidityUsd', label: 'Min liquidity', hint: 'No trading into thin pools.', unit: '$', group: 'Coin checks' },
  { key: 'earningsBlackoutDays', label: 'Earnings blackout', hint: 'Your agent supplies the earnings date from its Robinhood connection.', unit: 'days', group: 'Assets and timing' },
] as const;

// Shared labels for the ported Mission Control screens.
export const MISSION_LABELS = {
  "activity": "Activity",
  "limits": "Limits",
  "performance": "Performance",
  "connection": "Connection",
  "breadcrumb": "Breadcrumb",
  "missionControl": "Mission Control",
  "robinhoodMcp": "Robinhood (MCP)",
  "onChainAgent": "On-chain agent",
  "perpVenue": "Perp venue",
  "mcpAgent": "MCP agent",
  "waitingForFirstCall": "Waiting for first call",
  "resumeAgent": "Resume agent",
  "pauseAgent": "Pause agent",
  "disconnect": "Disconnect…",
  "reconnect": "Reconnect",
  "anOrderWasPlacedWithoutACheck": "An order was placed without a check.",
  "beforeEveryOrderCallEkoPreflightAnd": `Before every order, call ${APP_NAME} preflight and follow its decision. Journal the outcome with its preflightId.`,
  "instructionsCopied": "Instructions copied",
  "couldNotCopyInstructions": "Could not copy instructions.",
  "copyInstructions": "Copy instructions",
  "atAGlance": "At a glance",
  "checksInTheLast24Hours": "Checks in the last 24 hours",
  "protection": "Protection",
  "needsApproval": "Needs approval",
  "denied": "Denied",
  "above": "above ",
  "edit": "Edit",
  "presets": "Presets",
  "moneyAtWork": "Money at work",
  "notReported": "Not reported",
  "agentDetails": "Agent details",
  "atEachCheckInTheAgentReports": "At each check-in the agent reports its recent orders. Any without a matching preflight is flagged as an unchecked order.",
  "aboutThisLog": "About this log",
  "privateToYou": "Private to you",
  "entriesToday": "Entries today",
  "nextRoot": "Next root",
  "in": "in ",
  "s": "s",
  "storage": "Storage",
  "appendOnlyEncryptedPerUser": "Append-only · encrypted per user",
  "entriesAreCommittedOnChainAsPrivate": "Entries are committed on-chain as private hashes in 5-minute roots. Open Details to see the commitment and sharing state.",
  "limitsHit24h": "Limits hit, 24h",
  "renameAgent": "Rename agent",
  "name": "Name",
  "saveName": "Save name",
  "cancel": "Cancel",
  "aborterror": "AbortError",
  "retry": "Retry",
  "loadingAgent": "Loading agent",
  "agent": "Agent",
  "expired": "Expired",
  "expiresIn": "Expires in ",
  "sell": "Sell",
  "buy": "Buy",
  "usualOrder": "Usual order",
  "thisOneIs": "· this one is",
  "ruleHit": "Rule hit",
  "approvalaboveusd": "approvalAboveUsd",
  "preflight": "Preflight",
  "policyV": "· policy v",
  "openApproval": "Open approval",
  "preflightChecks": "Preflight checks",
  "expiredTheAgentWasToldNo": "Expired. The agent was told no.",
  "decidedElsewhere": "Decided elsewhere:",
  "back": "Back",
  "working": "Working…",
  "confirmApprove": "Confirm approve",
  "confirmDeny": "Confirm deny",
  "approve": "Approve",
  "deny": "Deny",
  "robinhoodAsksYouAgainIfItsTrade": "Robinhood asks you again if its trade approvals are on.",
  "theAgentGetsYourAnswerOnIts": "The agent gets your answer on its next call.",
  "pending": "Pending",
  "approvals": "Approvals",
  "waiting": "waiting",
  "decidedIn7Days": "decided in 7 days",
  "history": "History",
  "nothingWaitingYourAgentsAreInsideTheir": "Nothing waiting. Your agents are inside their limits.",
  "backToAgents": "Back to Agents",
  "recentDecisions": "Recent decisions",
  "expiry": "Expiry",
  "order": "Order",
  "rule": "Rule",
  "decision": "Decision",
  "noDecisionsYet": "No decisions yet.",
  "approvalLimits": "Approval limits",
  "perAgentPolicy": "Per agent policy",
  "above2": "Above ",
  "howApprovalsReachYou": "How approvals reach you",
  "notificationsOnlyTellYouSomethingIsWaiting": "Notifications only tell you something is waiting. You approve on the web, never inside Telegram. Without an answer, the approval expires and the agent is told no.",
  "notificationSettings": "Notification settings",
  "loadingApprovals": "Loading approvals",
  "reviewApproval": "Review approval",
  "yourAgentSClient": "Your agent’s client",
  "guardrailsEnforcedOnceReviewed": "Guardrails enforced once reviewed",
  "advisoryGuardrails": "Advisory guardrails",
  "harnessPreview": "Harness preview",
  "shipsAtTokenLaunch": "Ships at token launch",
  "copied": "Copied",
  "couldNotCopyCheckClipboardPermissions": "Could not copy. Check clipboard permissions.",
  "copy": "Copy",
  "balanced": "Balanced",
  "sessionKeyTransactionRevertedNoConnectionConfirmed": "Session-key transaction reverted. No connection confirmed.",
  "connectAnAgent": "Connect an agent",
  "noInstallPacksAreAvailableYet": "No install packs are available yet.",
  "setUp": "Set up",
  "oauthSignInNoKey": "OAuth sign-in, no key",
  "harnessApiKey": "Harness API key",
  "about": "· About",
  "minutes": "minutes",
  "platform": "Platform",
  "nameAndPreset": "Name and preset",
  "preset": "preset",
  "agentCreatedPolicyV": "Agent created · policy v",
  "creating": "Creating…",
  "createAgent": "Create agent",
  "generateAHarnessKey": "Generate a harness key",
  "theKeyTiesThisAgentToIts": "The key ties this agent to its policy and journal.",
  "keyShownOnceItCanTBe": "Key shown once. It can’t be revealed again.",
  "generating": "Generating…",
  "generateKey": "Generate key",
  "install": "Install",
  "addTheConnectorSignInWithThe": "Add the connector, sign in with the same wallet and choose the agent created above.",
  "theKeyGoesInTheAuthorizationHeader": "The key goes in the Authorization header.",
  "connectorUrl": "Connector URL",
  "mcpConfig": "MCP config",
  "harnessInstructions": "Harness instructions",
  "sessionKeyTransactionConfirmed": "Session-key transaction confirmed",
  "reviewAndSignSessionKeyPolicy": "Review and sign session-key policy",
  "testTheConnection": "Test the connection",
  "connected": "Connected",
  "weLlWaitForYourAgentS": "We’ll wait for your agent’s first call, then show it here.",
  "generateAKeyFirst": "Generate a key first.",
  "openJournal": "Open journal",
  "newAgent": "New agent",
  "appliedWhenItSCreated": "Applied when it’s created",
  "policyPreset": "Policy preset",
  "upTo": "Up to",
  "perOrder": "per order",
  "maxPosition": "Max position",
  "stopAfterADailyLossOf": "Stop after a daily loss of",
  "blocksCoinsFlagged": "Blocks coins flagged",
  "monitorAndDanger": "Monitor and Danger",
  "danger": "Danger",
  "maxRoundTripCost": "Max round-trip cost",
  "minLiquidity": "Min liquidity",
  "needsApprovalAbove": "Needs approval above",
  "deniedAboveApprovalLimit": "Denied above approval limit",
  "approvalsArriveAtTokenLaunchUntilThen": "Approvals arrive at token launch; until then, orders above the approval limit are denied, never left hanging.",
  "whatYourAgentGets": "What your agent gets",
  "mcpTools": "MCP tools",
  "senses": "Senses",
  "guardrails": "Guardrails",
  "flightRecorder": "Flight Recorder",
  "preflightIsARiskCheckAgainstYour": "Preflight is a risk check against your own policy, not advice.",
  "loadingPacks": "Loading packs",
  "oauthGrant": "OAuth grant",
  "harnessKey": "Harness key",
  "revoked": "Revoked",
  "oauth": "OAuth",
  "mcpAuthorizationHeader": "MCP · Authorization header",
  "usedBy": "Used by",
  "created": "Created",
  "lastUsed": "Last used",
  "notYet": "Not yet",
  "revokeGrant": "Revoke grant",
  "revoke": "Revoke",
  "robinhoodConnection": "Robinhood connection",
  "separateFromEko": `Separate from ${APP_NAME}`,
  "openRobinhood": "Open Robinhood",
  "onChainEnforcement": "On-chain enforcement",
  "safe": "Safe",
  "rolesModule": "Roles module",
  "role": "Role",
  "agentSigner": "Agent signer",
  "chain": "Chain",
  "permissionSetPreview": "Permission set preview",
  "ponsCurveTradesSitOutsideThisRole": "Pons curve trades sit outside this role.",
  "venueKey": "Venue key",
  "toCutTheAgentOffAtThe": "To cut the agent off at the venue, delete its trade-only API wallet there.",
  "scopes": "Scopes",
  "noScopeLetsEkoMoveFundsOr": `No scope lets ${APP_NAME} move funds or read your Robinhood account.`,
  "newHarnessKey": "New harness key",
  "createAKey": "Create a key",
  "revokeOauthGrant": "Revoke OAuth grant",
  "revokeHarnessKey": "Revoke harness key",
  "confirmRevoke": "Confirm revoke",
  "thisConnectionWillStopAuthenticatingWithEko": `This connection will stop authenticating with ${APP_NAME}. Remove it in the agent’s client too if you won’t reconnect.`,
  "sold": "Sold",
  "bought": "Bought",
  "of": "of ",
  "sessionStarted": "Session started",
  "check": "Check",
  "agentNote": "Agent note",
  "policyV2": "Policy v",
  "details": "Details",
  "committedOnChainAsAPrivateHash": "Committed on-chain as a private hash",
  "privateCommitmentPending": "Private commitment pending",
  "commitment": "Commitment",
  "sharing": "Sharing",
  "shared": "Shared",
  "all": "All",
  "checks": "Checks",
  "blocked": "Blocked",
  "orders": "Orders",
  "warnings": "Warnings",
  "showJournalEntries": "Show journal entries",
  "symbol": "Symbol",
  "filterBySymbol": "Filter by symbol",
  "liveNewEntriesAppearAtTheTop": "Live · new entries appear at the top",
  "pausedNoNewEntries": "Paused · no new entries",
  "disconnectedLogKept": "Disconnected · log kept",
  "noEntriesInThisWindow": "No entries in this window.",
  "loading": "Loading…",
  "olderEntries": "Older entries",
  "showingTheLatest": "Showing the latest",
  "entries": "entries.",
  "hide": "Hide",
  "reveal": "Reveal",
  "keyCopied": "Key copied",
  "copyKey": "Copy key",
  "iVeStoredTheKey": "I’ve stored the key",
  "dailyProfitAndLoss30Days": "Daily profit and loss, 30 days",
  "cumulativeProfitAndLoss30Days": "Cumulative profit and loss, 30 days",
  "today": "Today",
  "pLThatDay": "P&L that day",
  "cumulativePL": "Cumulative P&L",
  "performanceHasNotBeenReported": "Performance has not been reported.",
  "pAmpL30Days": "P&amp;L, 30 days",
  "text24h": "24h",
  "closedInProfit": "Closed in profit",
  "of2": "of",
  "closedTrades": "closed trades",
  "averageHold": "Average hold",
  "entryToExit": "Entry to exit",
  "deepestDrawdown": "Deepest drawdown",
  "worstDay": "Worst day",
  "cumulativePAmpL": "Cumulative P&amp;L",
  "text30DaysFromTheAgentSJournal": "30 days · from the agent’s journal reports",
  "dailyPAmpL": "Daily P&amp;L",
  "openPositions": "Open positions",
  "position": "Position",
  "size": "Size",
  "unrealised": "Unrealised",
  "total": "Total",
  "unset": "Unset",
  "custom": "Custom",
  "policyChangedElsewhereReviewAndSaveAgain": "Policy changed elsewhere — review and save again.",
  "preset2": "Preset",
  "fillsTheFieldsBelowReviewChangesBefore": "Fills the fields below. Review changes before saving.",
  "sizeAndLoss": "Size and loss",
  "coinChecks": "Coin checks",
  "assetsAndTiming": "Assets and timing",
  "enterANonnegativeNumber": "Enter a nonnegative number",
  "blockedVerdicts": "Blocked verdicts",
  "none": "None",
  "allowedAssets": "Allowed assets",
  "blockedAssets": "Blocked assets",
  "commaSeparatedAssets": "Comma-separated assets",
  "unsavedPolicyChanges": "Unsaved policy changes",
  "unsavedChanges": "unsaved changes",
  "savesAsV": "· saves as v",
  "discard": "Discard",
  "savePolicy": "Save policy",
  "whatPreflightChecks": "What preflight checks",
  "v": "v",
  "policySummary": "Policy summary",
  "largestOrder": "Largest order",
  "preflightAnswersAgainstYourPolicyAndJournals": "Preflight answers against your policy and journals every call. It’s a risk check against your rules, not advice.",
  "reviewPolicyChanges": "Review policy changes",
  "saving": "Saving…",
  "confirmSave": "Confirm save"
} as const;

export const MISSION_TEXT = {
  saved: (version: number) => `Saved as v${version}`,
  defaultAgent: (client: string) => `My ${client} agent`,
  daysAgo: (days: number) => `${days}d ago`,
  lastActive: (time: string) => `Last active ${time}`,
  clientVenue: (client: string, venue: string) => `${client} · trades on ${venue}`,
  paused: (name: string) => `Paused. Every order ${name} asks about is blocked, and it has been told to stop.`,
  disconnected: (name: string, robinhood: boolean) => `Disconnected. ${name}’s ${APP_NAME} keys are revoked.${robinhood ? ' Open Robinhood to disconnect this agent there too.' : ''}`,
  order: (side: string, amount: string, instrument: string) => `${side} ${amount} of ${instrument}`,
  today: (amount: string) => `${amount} today`,
  approve: (name: string, side: string, amount: string, instrument: string) => `Approve: ${name} may ${side} ${amount} of ${instrument}?`,
  deny: (name: string, instrument: string) => `Deny: ${name} is told no for ${instrument}.`,
  leverage: (leverage: number) => ` at ${leverage}×`,
};

export const CONNECT_STEPS = {
  connector: ['Open Customize → Connectors', 'Paste the MCP URL', `Click Connect, then approve on ${APP_NAME}`, 'Add the harness instructions'],
  key: ['Generate a harness key', `Add ${APP_NAME} to your MCP servers`, 'Give your agent the harness instructions', 'Check it’s connected'],
  approvals: 'Check trade approvals are on in Robinhood',
  connectorReturn: 'Your browser returns to the client’s registered callback. Add the harness instructions there, then return here to Verify.',
  keyConfig: 'The key goes in the Authorization header. Copy the config with your key filled in.',
  keyCheck: `Turn on the agent journal, then ask your agent to check in with ${APP_NAME}. Its first journal event will appear below.`,
  keyCheckBelow: 'Its first journal event will appear below.',
};
