export const SCAN_COPY = {
  title: 'Every move has a cause.', prompt: 'Paste any contract address or $ticker', submit: 'Scan',
  intro: 'Check buyer risk, exit costs and the evidence behind a verdict. No wallet needed.',
  invalid: 'Enter a contract address or $ plus 1–20 letters, numbers or underscores.',
  pending: 'Scanning… usually under 5 s', waiting: 'This scan is taking longer. Check again to reload the persisted result.',
  error: 'Could not load the scan. Nothing was sent to chain.', submitError: 'Could not start the scan. Nothing was sent to chain.',
  notFound: 'No coin found for this scan.', ambiguous: 'Choose the coin you meant', retry: 'Retry',
  unavailable: 'not checked yet', ageUnavailable: 'Age unavailable', scope: 'Robinhood Chain tokens: Pons launches and Uniswap pools.',
  refused: 'honeypots refused', missed: 'honeypots missed', since: 'Observed since', countersUnavailable: 'Observation counters are unavailable.',
  radar: 'Radar preview', radarEmpty: 'No indexed coins to preview yet.', radarError: 'Radar preview unavailable.',
  radarDelay: 'Data delay', openRadar: 'Open Radar', exit: 'Exit cost at $1K', flow: 'Buyer flow',
  harness: 'Add EKO to your Robinhood-connected agent', harnessBody: 'Senses, Guardrails, Loop Lab, Flight Recorder and Mission Control. External-agent guardrails are advisory.',
  connect: 'Connect an agent', drops: 'Weekly Drops', dropsBody: 'Explore planned features and their release gates.',
  result: 'Scan result', stale: 'Stale snapshot', refreshFailed: 'Refresh unavailable · prior snapshot retained',
  openCoin: 'Open coin', bags: 'Scan my bags', share: 'Share', copy: 'Copy link', copied: 'Link copied', copyFailed: 'Could not copy. Select the link below.',
  scanAgain: 'Scan another coin', evidence: 'Evidence and playbooks', costs: 'Exit costs', allEvidence: 'Open all reasons and evidence',
  receipt: 'Verify receipt', notChecked: 'not checked yet',
} as const;
