export const SETTINGS_COPY = {
  accountChanged: 'Account changed. Reload your preferences.',
  title: 'Settings', subtitle: 'Trading, notifications, display, and harness data.', sections: 'Settings sections',
  trading: 'Trading', wallet: 'Wallet & network', notifications: 'Notifications', plan: 'Plan and referrals', display: 'Display', privacy: 'Privacy & data', about: 'Help and About',
  defaultMode: 'Default mode', defaultModeNote: 'Your preferred mode. Live trading still requires the wallet and trading checks.',
  amountsNote: 'Dollar presets for the trade panel. Up to 6.', sellPresets: 'Sell presets', sellPreset: 'Sell percentage', sellPresetsNote: 'Percentages of your holding. Up to 6.',
  slippagePresets: 'Slippage presets', slippagePreset: 'Slippage preset', slippagePresetsNote: 'Whole basis points from 1 to 500. Up to 5.',
  connect: 'Connect wallet', connectNote: 'Connect and verify your wallet to manage this account section.',
  verified: 'SIWE session verified for this wallet.', unverified: 'No verified SIWE session for the connected wallet.', chain: 'Connected chain:', manageWallet: 'Manage wallet',
  signOut: 'Sign out', signingOut: 'Signing out…', logoutError: 'Could not sign out. Your session is still here. Try again.',
  viewPlan: 'View plan and referrals', density: 'Density', deviceOnly: 'Saved on this device.', comfortable: 'Comfortable', compact: 'Compact',
  motion: 'Reduce motion', motionOptions: { system: 'System', on: 'Reduce', off: 'Full motion' }, humanMarkers: 'Human markers',
  replayTour: 'Replay the tour', version: 'Version', legal: { terms: 'Terms', privacy: 'Privacy', risk: 'Risk disclosure', ai: 'AI disclosure' },
  sharing: 'Default journal sharing', sharingUnavailable: 'Journal entries are private unless you explicitly share them. Default sharing preferences are not available yet.',
  deleteTitle: 'Delete my harness data', deleteNote: 'Deletion destroys access to your private harness data and revokes harness credentials. It cannot be undone. Public on-chain hashes and previously shared data remain.',
  deletePrompt: 'Type DELETE to confirm', deleteWord: 'DELETE', cancel: 'Cancel', deleting: 'Deleting…', deleted: 'Harness data deleted.',
  deleteError: 'Could not delete harness data. Completion is unconfirmed; try again.',
  tradingForm: 'Trading preferences', tradeAmounts: 'Trade amounts', tradeAmount: 'Trade amount',
  slippage: 'Max slippage (Live)', slippageNote: 'A live swap is cancelled if the price moves further than this before it lands.', slippageLabel: 'Default slippage in basis points',
  confirmation: 'Ask before large Live trades', confirmationNote: 'Live trades worth more than this wait for an extra Confirm before your wallet opens.', confirmationLabel: 'Large trade confirmation threshold in USD',
  invalidAmount: 'Each amount must be a positive number', invalidPercent: 'Each percentage must be between 1 and 100', invalidBps: 'Whole basis points from 1 to 500', positive: 'Must be a positive amount',
  listLength: (min: number, max: number) => `Between ${min} and ${max} values`,
  notSaved: 'Preferences not saved', invalidValue: 'Invalid value', saved: 'Preferences saved', savedNote: (count: number) => `${count} setting${count === 1 ? '' : 's'} updated.`,
  fix: 'Fix the highlighted settings to save.', unsaved: 'Unsaved changes', allSaved: 'All changes saved', restore: 'Restore defaults', discard: 'Discard', save: 'Save', add: 'Add',
  removeLabel: (label: string, index: number) => `Remove ${label.toLowerCase()} ${index + 1}`, addLabel: (label: string) => `Add ${label.toLowerCase()}`,
} as const;

export const PLAN_COPY = {
  title: 'Plan and referrals', back: 'Settings', loading: 'Loading plan…', launch: 'Free during launch week', tokenLive: 'Tiers start tomorrow',
  launchNote: 'Every shipped feature is free during launch week, including a 0% terminal fee until token day.',
  feeLaunch: 'Terminal fee: 0% during launch week.', feeCurve: 'Terminal fee: 0% on Pons-curve trades.', feeUniswap: 'on Uniswap-routed trades', feeUniswapZero: 'Terminal fee: 0% on Uniswap-routed trades.',
  referralTitle: 'Referral attribution', referralNote: 'Referral codes and attribution are recorded from launch. Trial bonuses start when referrals open.',
  referralBonus: 'You and your friend each get +30 minutes when they make their first guarded trade or connect an agent.',
  referralLoading: 'Loading referral attribution…', referralError: 'Could not load referral attribution. Try again.',
  copy: 'Copy referral link', copied: 'Referral link copied.', copyError: 'Could not copy. Select and copy the link above.', shareX: 'Share on X', shareTelegram: 'Share on Telegram',
  referred: 'Referred wallets', qualified: 'Qualified referrals', bonus: 'Bonus minutes', retry: 'Retry',
  tiers: 'Tiers', tierNames: { listener: 'Listener', reader: 'Reader', oracle: 'Oracle', source: 'Source' },
  minHeld: 'Minimum balance held over 24 h', unavailable: 'Not available', requirement: 'Hold ≥', hold: 'EKO for 24 h', amountsNote: 'Tier requirements are reviewed monthly and only ever lowered.',
  fee: 'Terminal fee', agents: 'Agents', research: 'Deep Research runs per day', backtests: 'Rule Lab runs per day', realtime: 'Real-time access', yes: 'Yes', no: 'No',
  trial: 'Trial', eligible: 'Connect to start 30 minutes of full access.', used: 'Trial used.',
  ineligible: 'Trials need a wallet with 7+ days of history, 10+ Robinhood Chain transactions, or $20+ balance.', trialEnded: 'Trial ended.',
  futurePerk: (drop: string) => `shipping in ${drop}`,
} as const;
