export const TRADE_COPY = {
  connect: 'Connect wallet to trade.',
  paused: 'Live trading is paused. Scans and quotes still work.',
  not_allowlisted: 'Live trading is open to allowlisted wallets during the beta.',
  trade_cap_exceeded: 'This amount exceeds the per-trade cap for this wallet.',
  refused: 'The guard refused this trade. Nothing was sent.',
  stale: 'Data is stale — trading paused.',
  expired: 'Quote expired — requesting a fresh quote.',
  quoteOnly: "Trading for this coin isn't open here yet.",
  signingUnavailable: 'Wallet signing is not available here yet.',
  unavailable: 'Quote unavailable. Nothing was sent. Retry when checks are available.',
  wallet_mismatch: 'Wallet changed — sign in again or switch back.',
  wrongNetwork: 'Switch your wallet to chain 4663 before trading.',
  sanctioned: 'Trading is unavailable for this wallet.',
  invalid: 'Enter a positive amount and slippage between 0 and 99.99%.',
  loading: 'Requesting quote…',
  refresh: 'Refreshing quote…',
  indicative: 'Indicative quote — wallet-bound checks are required before trading.',
  config: 'Trading configuration unavailable.',
  acknowledge: 'I understand — continue',
  review: 'Review warnings',
  changed: 'Quote changed. Review the new numbers and tap again.',
  confirm: 'Confirm trade',
  confirmLarge: 'This trade exceeds your confirmation threshold. Review the amount and tap Confirm trade.',
  recovery: 'Check the existing order before starting another trade.',
  retry: 'Retry quote',
  zeroLaunch: '0% during launch week',
  busy: 'Trade in progress…',
  cap: (cap: number) => `Max $${cap.toLocaleString('en-US')} per trade during launch.`,
  warnings: (mode: string) => `${mode} treats these checks as warnings. Acknowledgement applies to this quote only.`,
  statuses: {
    awaiting_signature: 'Awaiting wallet signature.',
    submitted: 'Submitted — waiting for confirmation.',
    confirmed: 'Confirmed on-chain.',
    rejected: 'Rejected in wallet.',
    expired: 'Order expired. Request a fresh quote.',
    failed: 'Failed on-chain — no trade happened (gas was spent).',
  },
};
export const TRADE_LABELS = {
  side: 'Trade side', buy: 'Buy', sell: 'Sell', amount: 'Custom trade amount', slippage: 'Slippage (%)',
  mode: 'Mode', pay: 'You pay', receive: 'Expected received (raw units)', minimum: 'Minimum received (raw units)',
  input: 'Input (raw units)', value: 'Native value (wei)', price: 'Price', route: 'Route', fee: 'Terminal fee',
  buyTax: 'Buy tax', sellTax: 'Sell tax', exit: 'Exit cost at this size', impact: 'Price impact', network: 'Network fee (execution + L1 data)',
  tier: 'Tier', block: 'Quote block', guard: 'Guard checks', checks: (n: number) => `${n} ${n === 1 ? 'check' : 'checks'} passed`,
  venues: { uniswap_v3: 'Uniswap v3', uniswap_v4: 'Uniswap v4', pons_curve: 'Pons curve', other: 'Other' },
};
