import { WALLET_LABELS_LATER } from '../../copy/availability';
import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import type { Address, Bar, ChartMarker, WalletLabel } from '@eko/shared';
import { Seg, WALLET_LABEL_WORD } from '../ui';
import { formatCoinPrice } from '../../lib/format';
import { TimeframeControls } from './TimeframeControls';
import { ChartCore } from './chartCore';
import { COIN_TIMEFRAMES, type CoinTimeframe, type View } from './coinMath';
import { FlowLayer, Glyph } from './FlowLayer';
export function ChartStage(p:{market:string;timeframe:CoinTimeframe;onTimeframe:(tf:CoinTimeframe)=>void;bars:Bar[];markers:ChartMarker[];supply:number;verdict:ReactNode;delayedSec?:number;ownToken?:boolean;burnWallet?:Address;launchTs?:number;crewsEnabled?:boolean;labelsUnavailable?:boolean}){
 const readout=useRef<HTMLSpanElement>(null),plot=useRef<HTMLDivElement>(null),surface=useRef<HTMLDivElement>(null),scale=useRef<HTMLDivElement>(null),[core,setCore]=useState<ChartCore|null>(null),[mode,setMode]=useState<'Line'|'Candles'>('Line'),[axis,setAxis]=useState('Price'),[show,setShow]=useState<Record<WalletLabel,boolean>>({declared_agent:true,likely_agent:true,crew:true,human:false});
 const drag=useRef<{x:number;y:number;view:View;k:number;kind:'plot'|'scale'}|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),pinch=useRef<number|null>(null),lastTf=useRef<CoinTimeframe|null>(null);
 useLayoutEffect(()=>{const c=new ChartCore(plot.current!);setCore(c);if(import.meta.env.DEV)(plot.current as HTMLDivElement & { __ekoChartCore?:ChartCore }).__ekoChartCore=c;return()=>c.destroy();},[p.market]);
 useLayoutEffect(()=>{if(!core)return;const changed=lastTf.current!==p.timeframe;core.setData(p.bars,p.timeframe,!changed);if(changed&&p.bars.length)core.animate();if(p.bars.length)lastTf.current=p.timeframe;},[core,p.bars,p.timeframe]);
 useLayoutEffect(()=>{if(core){core.setMode(mode);core.axisSupply=axis==='Price'?1:p.supply;core.scheduleRedraw();}},[core,mode,axis,p.supply]);
 useLayoutEffect(()=>{if(!core)return;const sync=()=>{const b=core.data[core.hoverIndex]??core.data.at(-1);if(!b||!readout.current)return;const fmt=(v:number)=>axis==='Price'?formatCoinPrice(v):`$${(v*p.supply/1e6).toFixed(2)}M`;readout.current.textContent=`O ${fmt(b.o)} H ${fmt(b.h)} L ${fmt(b.l)} C ${fmt(b.c)}`;};sync();return core.onRedraw(sync);},[core,axis,p.supply]);
 useEffect(()=>{if(!core)return;const el=surface.current!,sc=scale.current!;
 const wheel=(e:WheelEvent)=>{e.preventDefault();const x=e.clientX-plot.current!.getBoundingClientRect().left;if(Math.abs(e.deltaX)>Math.abs(e.deltaY)&&!e.ctrlKey)core.pan(-e.deltaX);else core.zoom(Math.exp(e.deltaY*(e.ctrlKey?.01:.0018)),x);};
 const stretch=(e:WheelEvent)=>{e.preventDefault();core.stretch(e.deltaY);};el.addEventListener('wheel',wheel,{passive:false});sc.addEventListener('wheel',stretch,{passive:false});return()=>{el.removeEventListener('wheel',wheel);sc.removeEventListener('wheel',stretch);};},[core]);
 const up=(id:number)=>{pointers.current.delete(id);pinch.current=null;drag.current=null;};
 return <div className="cchart"><div className="plate coin-chart" ref={plot} data-timeframe={p.timeframe}>
 <div ref={surface} className="cc-surface" tabIndex={0} role="application" aria-roledescription="chart" aria-label={`${p.market} price chart. Plus and minus zoom, arrow keys move, 0 resets. Keys 1 to 8 select timeframe.`}
 onKeyDown={e=>{if(!core||e.target!==e.currentTarget)return;const key=e.key;if(key==='+'||key==='=')core.zoom(.8);else if(key==='-'||key==='_')core.zoom(1.25);else if(key==='0')core.reset();else if(key==='ArrowLeft'||key==='ArrowRight')core.pan((key==='ArrowLeft'?1:-1)*core.paneWidth()*.1);else if(/^[1-8]$/.test(key))p.onTimeframe(COIN_TIMEFRAMES[Number(key)-1]);else return;e.preventDefault();e.stopPropagation();}}
 onPointerDown={e=>{if(!core)return;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});drag.current={x:e.clientX,y:e.clientY,view:{...core.view},k:core.scale,kind:'plot'};}}
 onPointerMove={e=>{if(!core)return;if(!pointers.current.has(e.pointerId)){core.hoverAt(e.clientX-plot.current!.getBoundingClientRect().left);return;}pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const pts=[...pointers.current.values()];if(pts.length===2){const distance=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(pinch.current)core.zoom(pinch.current/distance,(pts[0].x+pts[1].x)/2-plot.current!.getBoundingClientRect().left);pinch.current=distance;return;}const d=drag.current;if(d)core.pan(e.clientX-d.x,d.view);}}
 onPointerUp={e=>up(e.pointerId)} onPointerCancel={e=>up(e.pointerId)} onPointerLeave={()=>{if(core){core.hoverIndex=-1;core.scheduleRedraw();}}} onDoubleClick={()=>core?.reset()}/>
 <div ref={scale} className="cc-scale" aria-label="Price scale" title="Drag or scroll to stretch the price scale · double-click to fit" onPointerDown={e=>{if(!core)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,view:core.view,k:core.scale,kind:'scale'};}} onPointerMove={e=>{const d=drag.current;if(core&&d?.kind==='scale')core.stretch((e.clientY-d.y)*3,d.k);}} onPointerUp={e=>up(e.pointerId)} onPointerCancel={e=>up(e.pointerId)} onDoubleClick={()=>{if(core){core.scale=1;core.shift=0;core.scheduleRedraw();}}}/>
 {core&&!p.labelsUnavailable&&<FlowLayer {...p} core={core} show={show}/>}
 <div className="chart-top"><div className="chart-read">{p.verdict}<span className="num coin-ohlc" ref={readout} aria-hidden="true"/>{!!p.delayedSec&&<span className="tag">Delayed ~{p.delayedSec} s</span>}</div><div className="chart-ctl"><Seg options={['Line','Candles']} value={mode} onChange={v=>setMode(v as typeof mode)} label="Chart type"/><TimeframeControls value={p.timeframe} onChange={p.onTimeframe}/><Seg options={['Price','Market cap']} value={axis} onChange={setAxis} label="Axis"/></div></div>
 </div><div className="coin-chart-phone-options"><Seg options={['Line','Candles']} value={mode} onChange={v=>setMode(v as typeof mode)} label="Chart type"/><Seg options={['Price','Market cap']} value={axis} onChange={setAxis} label="Axis"/></div>
 <div className="chart-flowkeys"><span className="muted">Show trades by</span>{(Object.keys(show) as WalletLabel[]).map(label=><label className="check" key={label}><input type="checkbox" disabled={p.labelsUnavailable} title={p.labelsUnavailable ? WALLET_LABELS_LATER : undefined} checked={!p.labelsUnavailable && show[label]} onChange={e=>setShow({...show,[label]:e.target.checked})}/><Glyph label={label}/>{WALLET_LABEL_WORD[label]}</label>)}{p.labelsUnavailable && <span className="muted">{WALLET_LABELS_LATER}</span>}<span className="cc-hint">Scroll to zoom · drag to move · drag the price scale to stretch it</span><span className="cc-zoom" role="group" aria-label="Zoom"><button className="btn btn-sm btn-ghost" aria-label="Reset chart" onClick={()=>core?.reset()}>Reset</button><button className="iconbtn" aria-label="Zoom out" onClick={()=>core?.zoom(1.25)}>−</button><button className="iconbtn" aria-label="Zoom in" onClick={()=>core?.zoom(.8)}>+</button></span></div></div>;
}
